# Generated by Django 5.2 on 2025-04-15 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('VENDOR', 'Vendor-specific'), ('GENERAL', 'General (Shared across vendors)')], default='GENERAL', max_length=10),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='general_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_food_items', to='restaurant.category'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='vendor_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_food_items', to='restaurant.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurant.vendor'),
        ),
    ]
